"""add salary and remarks

Revision ID: 73c0012fb40c
Revises: 938854c11439
Create Date: 2026-09-07 20:37:27.331468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c0012fb40c'
down_revision: Union[str, Sequence[str], None] = '938854c11439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('salary', sa.Float(), nullable=True))
    op.add_column('job_applications', sa.Column('remarks', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'remarks')
    op.drop_column('job_applications', 'salary')
    # ### end Alembic commands ###
