"""make optional job fields nullable

Revision ID: 938854c11439
Revises: 277bdc54ad02
Create Date: 2026-08-28 21:06:10.510378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938854c11439'
down_revision: Union[str, Sequence[str], None] = '277bdc54ad02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_applications', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_applications', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
